# Generated by Django 4.2.7 on 2025-11-05 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="생년월일"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="전화번호"
                    ),
                ),
                (
                    "preferred_district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="선호 지역"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "남성"), ("F", "여성"), ("O", "기타")],
                        max_length=10,
                        verbose_name="성별",
                    ),
                ),
                (
                    "preferred_treatments",
                    models.TextField(blank=True, verbose_name="관심 치료"),
                ),
                (
                    "budget_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "50만원 이하"),
                            ("medium", "50-200만원"),
                            ("high", "200만원 이상"),
                        ],
                        max_length=20,
                        verbose_name="예산 범위",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 프로필",
                "verbose_name_plural": "사용자 프로필들",
                "db_table": "accounts_user_profile",
            },
        ),
    ]
