steps:
  # 1. Install frontend dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'frontend'

  # 2. Build frontend
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'frontend'
    env:
      - 'VITE_API_URL=https://dental-ai-backend-602563947939.asia-northeast3.run.app/api' # Replace with your actual backend URL

  # 3. Run Django collectstatic
  - name: 'python:3.9'
    entrypoint: 'bash'
    args: [
      '-c',
      'pip install -r requirements.txt && python manage.py collectstatic --noinput'
    ]

  # 4. Remove frontend sources before deploy to stay under App Engine file limit
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: [
      '-c',
      'rm -rf frontend && echo "Removed frontend directory after collectstatic"'
    ]

  # 5. Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: [
      '-c',
      'apt-get update && apt-get install -y python3-pip && pip3 install -r requirements.txt && gcloud app deploy --appyaml=app.yaml --version=$BUILD_ID --project=$PROJECT_ID --no-promote'
    ]
    dir: '.'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

timeout: '3600s'
