# Generated by Django 4.2.7 on 2025-11-04 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionalPriceStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district", models.CharField(max_length=100, verbose_name="지역구")),
                (
                    "treatment_type",
                    models.CharField(max_length=100, verbose_name="치료 종류"),
                ),
                ("min_price", models.IntegerField(verbose_name="최소 가격")),
                ("max_price", models.IntegerField(verbose_name="최대 가격")),
                (
                    "avg_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="평균 가격"
                    ),
                ),
                ("median_price", models.IntegerField(verbose_name="중간값 가격")),
                ("sample_count", models.IntegerField(verbose_name="샘플 수")),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 업데이트"),
                ),
            ],
            options={
                "verbose_name": "지역별 가격 통계",
                "verbose_name_plural": "지역별 가격 통계들",
                "db_table": "analysis_regional_price_stats",
                "indexes": [
                    models.Index(
                        fields=["district", "treatment_type"],
                        name="analysis_re_distric_0c92bd_idx",
                    )
                ],
                "unique_together": {("district", "treatment_type")},
            },
        ),
        migrations.CreateModel(
            name="SentimentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="가격 점수"
                    ),
                ),
                (
                    "skill_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="실력 점수"
                    ),
                ),
                (
                    "kindness_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="친절도 점수"
                    ),
                ),
                (
                    "waiting_time_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="대기시간 점수"
                    ),
                ),
                (
                    "facility_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="시설 점수"
                    ),
                ),
                (
                    "overtreatment_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="과잉진료 점수"
                    ),
                ),
                (
                    "model_version",
                    models.CharField(max_length=50, verbose_name="모델 버전"),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="신뢰도"
                    ),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="분석일"),
                ),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.review",
                        verbose_name="리뷰",
                    ),
                ),
            ],
            options={
                "verbose_name": "감성 분석",
                "verbose_name_plural": "감성 분석들",
                "db_table": "analysis_sentiment",
                "indexes": [
                    models.Index(
                        fields=["analyzed_at"], name="analysis_se_analyze_fbce96_idx"
                    ),
                    models.Index(
                        fields=["model_version"], name="analysis_se_model_v_6cf0b7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treatment_type",
                    models.CharField(
                        choices=[
                            ("scaling", "스케일링"),
                            ("implant", "임플란트"),
                            ("root_canal", "신경치료"),
                            ("orthodontics", "교정"),
                            ("whitening", "미백"),
                            ("extraction", "발치"),
                            ("filling", "충치치료"),
                            ("crown", "크라운"),
                            ("bridge", "브릿지"),
                            ("denture", "틀니"),
                            ("other", "기타"),
                        ],
                        max_length=100,
                        verbose_name="치료 종류",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="가격")),
                (
                    "currency",
                    models.CharField(default="KRW", max_length=3, verbose_name="통화"),
                ),
                (
                    "extraction_confidence",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="추출 신뢰도"
                    ),
                ),
                (
                    "extraction_method",
                    models.CharField(
                        choices=[
                            ("regex", "정규표현식"),
                            ("ner", "NER 모델"),
                            ("manual", "수동 입력"),
                        ],
                        max_length=50,
                        verbose_name="추출 방법",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="검증됨"),
                ),
                (
                    "is_outlier",
                    models.BooleanField(default=False, verbose_name="이상치"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="clinics.clinic",
                        verbose_name="치과",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.review",
                        verbose_name="리뷰",
                    ),
                ),
            ],
            options={
                "verbose_name": "가격 데이터",
                "verbose_name_plural": "가격 데이터들",
                "db_table": "analysis_price",
                "indexes": [
                    models.Index(
                        fields=["treatment_type"], name="analysis_pr_treatme_a0d519_idx"
                    ),
                    models.Index(
                        fields=["clinic", "treatment_type"],
                        name="analysis_pr_clinic__24ff3d_idx",
                    ),
                    models.Index(
                        fields=["is_verified", "is_outlier"],
                        name="analysis_pr_is_veri_415f6f_idx",
                    ),
                ],
            },
        ),
    ]
