# Generated by Django 4.2.7 on 2025-11-04 06:11

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="치과명")),
                ("address", models.TextField(verbose_name="주소")),
                ("district", models.CharField(max_length=100, verbose_name="지역구")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="위도",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="경도",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="전화번호"
                    ),
                ),
                (
                    "has_parking",
                    models.BooleanField(default=False, verbose_name="주차 가능"),
                ),
                (
                    "night_service",
                    models.BooleanField(default=False, verbose_name="야간 진료"),
                ),
                (
                    "weekend_service",
                    models.BooleanField(default=False, verbose_name="주말 진료"),
                ),
                (
                    "total_reviews",
                    models.IntegerField(default=0, verbose_name="총 리뷰 수"),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="평균 평점",
                    ),
                ),
                (
                    "naver_place_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="네이버 플레이스 ID"
                    ),
                ),
                (
                    "google_place_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="구글 플레이스 ID"
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "치과",
                "verbose_name_plural": "치과들",
                "db_table": "clinics_clinic",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="clinics_cli_search__90ee92_gin"
                    ),
                    models.Index(
                        fields=["district"], name="clinics_cli_distric_aecfb7_idx"
                    ),
                    models.Index(
                        fields=["total_reviews"], name="clinics_cli_total_r_1b7462_idx"
                    ),
                ],
            },
        ),
    ]
