# Generated by Django 4.2.7 on 2025-11-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="business_hours",
            field=models.TextField(blank=True, verbose_name="운영시간"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="description",
            field=models.TextField(blank=True, verbose_name="설명"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="facilities",
            field=models.TextField(blank=True, verbose_name="시설정보"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="검증됨"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="specialties",
            field=models.TextField(blank=True, verbose_name="전문분야"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="website",
            field=models.URLField(blank=True, verbose_name="웹사이트"),
        ),
    ]
