# Generated by Django 4.2.7 on 2025-11-04 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district", models.CharField(max_length=100, verbose_name="지역구")),
                (
                    "treatment_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="치료 종류"
                    ),
                ),
                (
                    "recommended_clinics",
                    models.JSONField(verbose_name="추천된 치과 목록"),
                ),
                (
                    "algorithm_version",
                    models.CharField(max_length=50, verbose_name="알고리즘 버전"),
                ),
                (
                    "request_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="요청 IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="사용자 에이전트"),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="응답 시간(ms)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "추천 로그",
                "verbose_name_plural": "추천 로그들",
                "db_table": "recommendations_log",
            },
        ),
        migrations.CreateModel(
            name="RecommendationFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("helpful", "도움됨"),
                            ("not_helpful", "도움안됨"),
                            ("inaccurate", "부정확함"),
                            ("missing_info", "정보부족"),
                        ],
                        max_length=20,
                        verbose_name="피드백 유형",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="코멘트")),
                (
                    "did_visit",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="실제 방문"
                    ),
                ),
                (
                    "visit_rating",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="방문 후 평점"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinics.clinic",
                        verbose_name="치과",
                    ),
                ),
                (
                    "recommendation_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommendations.recommendationlog",
                        verbose_name="추천 로그",
                    ),
                ),
            ],
            options={
                "verbose_name": "추천 피드백",
                "verbose_name_plural": "추천 피드백들",
                "db_table": "recommendations_feedback",
            },
        ),
        migrations.CreateModel(
            name="ClinicScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_competitiveness",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="가격 경쟁력"
                    ),
                ),
                (
                    "medical_skill",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="의료진 실력"
                    ),
                ),
                (
                    "overtreatment_risk",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="과잉진료 위험도"
                    ),
                ),
                (
                    "patient_satisfaction",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="환자 만족도"
                    ),
                ),
                (
                    "comprehensive_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="종합 점수"
                    ),
                ),
                (
                    "calculation_version",
                    models.CharField(max_length=50, verbose_name="계산 버전"),
                ),
                (
                    "last_calculated",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 계산일"),
                ),
                (
                    "total_reviews_analyzed",
                    models.IntegerField(default=0, verbose_name="분석된 리뷰 수"),
                ),
                (
                    "price_data_points",
                    models.IntegerField(
                        default=0, verbose_name="가격 데이터 포인트 수"
                    ),
                ),
                (
                    "clinic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinics.clinic",
                        verbose_name="치과",
                    ),
                ),
            ],
            options={
                "verbose_name": "치과 점수",
                "verbose_name_plural": "치과 점수들",
                "db_table": "recommendations_clinic_score",
            },
        ),
        migrations.AddIndex(
            model_name="recommendationlog",
            index=models.Index(
                fields=["user", "created_at"], name="recommendat_user_id_dfb0ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationlog",
            index=models.Index(
                fields=["district", "created_at"], name="recommendat_distric_d91a48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationlog",
            index=models.Index(
                fields=["algorithm_version"], name="recommendat_algorit_d6c176_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recommendationfeedback",
            unique_together={("recommendation_log", "clinic")},
        ),
        migrations.AddIndex(
            model_name="clinicscore",
            index=models.Index(
                fields=["comprehensive_score"], name="recommendat_compreh_1c6d13_idx"
            ),
        ),
    ]
