# Generated by Django 4.2.7 on 2025-11-04 06:11

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("naver", "네이버 플레이스"),
                            ("google", "구글 맵"),
                            ("manual", "수동 입력"),
                        ],
                        max_length=20,
                        verbose_name="출처",
                    ),
                ),
                ("original_text", models.TextField(verbose_name="원본 텍스트")),
                (
                    "processed_text",
                    models.TextField(blank=True, verbose_name="전처리된 텍스트"),
                ),
                (
                    "original_rating",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="원본 평점"
                    ),
                ),
                (
                    "review_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="리뷰 작성일"
                    ),
                ),
                (
                    "reviewer_hash",
                    models.CharField(max_length=64, verbose_name="리뷰어 해시"),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="외부 플랫폼 ID"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="전처리 완료"),
                ),
                (
                    "is_duplicate",
                    models.BooleanField(default=False, verbose_name="중복 리뷰"),
                ),
                (
                    "is_flagged",
                    models.BooleanField(default=False, verbose_name="플래그됨"),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="clinics.clinic",
                        verbose_name="치과",
                    ),
                ),
            ],
            options={
                "verbose_name": "리뷰",
                "verbose_name_plural": "리뷰들",
                "db_table": "reviews_review",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="reviews_rev_search__2d1bb8_gin"
                    ),
                    models.Index(
                        fields=["clinic", "is_processed"],
                        name="reviews_rev_clinic__6861de_idx",
                    ),
                    models.Index(
                        fields=["source", "created_at"],
                        name="reviews_rev_source_f17dd0_idx",
                    ),
                    models.Index(
                        fields=["reviewer_hash"], name="reviews_rev_reviewe_53e01a_idx"
                    ),
                ],
                "unique_together": {("clinic", "external_id", "source")},
            },
        ),
    ]
